### ISSUE TITLE
Browse Cards table needs to map the mana_cost column to mana symbols or strings

### ISSUE THREAD

**Issue by calford16** [jricha22/cs6920#15]

**Comment by jricha22** [comment]
What is in the column is what is already what is returned by the manacost api call.  We can fabricate mana cost display in Javascript from what is already there, or the card API can be changed to filter mana cost down to a string if that makes things easier.

**Comment by jricha22** [comment]
Card detail now returns user friendly "mana_string" (eg "3BBG" for 3 colorless, 2 blue, 1 green).  Use that.

**Comment by calford16** [comment]
Table now displays user friendly "mana_string"
