### ISSUE TITLE
ng-Resource needs to supply cards to Browse Cards table based on parameters

### ISSUE THREAD

**Issue by calford16** [jricha22/cs6920#16]
ng-Resource only returns first five cards (alphabetically) from the API return. Need to include limit & offset parameters in the ng-Resource call.

**Comment by jricha22** [comment]
Use AngularUI pagination tool. Track current offset in Angular scope.  AngularUI docs have really good examples of how to use the pagination widget.

**Comment by calford16** [comment]
I have taken the angular-bootstrap UI approach. It looks like the pagination is all setup to work properly on my local file (haven't pushed yet), only problem is the pagination will crash because it attempts to slice the data to bring up the right entries for the pages but the data is provided out of sync by ng-resource. This leads to it crashing while trying to slice null data basically. Working out how to get the pagination to wait for ng-resource to finish loading.
