### ISSUE TITLE
Search filter on Browse Cards page shouldn't search JSON data not shown in the table.

### ISSUE THREAD

**Issue by calford16** [jricha22/cs6920#17]

**Comment by jricha22** [comment]
Search filter will be applied on the back end, I just haven't added it yet.

Web app can simply display everything that is returned by the API call.

**Comment by calford16** [comment]
The search appears to be working well so far on client side using angular. I can probably eliminate the additional hidden data pretty easy.

**Comment by jricha22** [comment]
We have a relational database, we should use it. Searches are what databases do.

Right now we only have a few hundred cards.  What if we add in all sets and the number of cards grows to tens of thousands?  Loading them all in the browser and searching in Javascript would slow to a crawl if it works at all...

Also, Dr Yoder made a point about keeping logic out of the GUI as much as possible.  The javascript code is the GUI.

I will have search done Saturday morning (I have it mostly done now but want to customize it and write tests).

**Comment by jricha22** [comment]
Search API is ready, here is documentation on params:

```
?color=Red,Blue returns all red or blue cards

?manalimt=5 returnes cards with cost 5 or less

?color=Red,Blue&manalimit=5&limit=10 returns the first 10 red or blue cards with cost 5 or less

?color=Red,Blue&manalimit=5&limit=10&offset=10 returns 10 cards red or blue cards with cost 5 or less, skipping the first 10 results
```

**Comment by calford16** [comment]
Filtering now uses the API params.
