### ISSUE TITLE
Create API to allow a new account to be created in the database

### ISSUE THREAD

**Issue by wdavids1** [jricha22/cs6920#18]

**Comment by jricha22** [comment]
Added api/core/create-account endpoint.  It accepts a POST request that contains {"username": <username>, "password": <password>, "first_name": <fname>, "last_name": <lname>, "email": <email>}.

Returns 400 if not all 5 attributes are in the POST or if any other than email are null strings.  Email can be null string.

Returns 403 if username already exists.

It logs the newly created user in and returns the user profile if successful.
