### ISSUE TITLE
Create API to allow cards to be added to current user’s deck assuming standard deck rules

### ISSUE THREAD

**Issue by calford16** [jricha22/cs6920#24]

**Comment by jricha22** [comment]
API is api/collect/deck-add-card/<id>/ to add card with that id to deck.  This is an empty POST.

Will return 400 if you try to add more than are in the collection or to add more than 4 basic lands to the deck.  If collection cards are deleted with the collection API, the deck cards are reduced as necessary.  Collection model has "in_deck" count which counts how many of the owned cards are in deck.
