### ISSUE TITLE
Create database insert query for adding a new user

### ISSUE THREAD

**Issue by wdavids1** [jricha22/cs6920#3]

**Comment by jricha22** [comment]
New users can be added through the admin page by a superuser at localhost:8000/admin

**Comment by calford16** [comment]
Does this allow new users to hit the "create new account" button to ask the admin to create a new account? Would we then have to go in manually and add them?

**Comment by jricha22** [comment]
No, I was thinking we would add a story about signing up new users in a later iteration.  I thought we were going to focus on the app contents first with an entirely manual user registration then add on to that later the ability to create new accounts dynamically.

Maybe I misunderstood what we were shooting for in iteration 1? If so we can reopen this and design something more than using the admin panel...
