### ISSUE TITLE
Extend the database and create the API to allow a deck to be shared publically.

### ISSUE THREAD

**Issue by wdavids1** [jricha22/cs6920#49]

**Comment by jricha22** [comment]
The deck should be given a name so that they can be listed by name for others to view.

**Comment by jricha22** [comment]
Added model and API calls to post and delete the users deck.  Pass the name as the last part of the url:

POST: api/collect/publish-deck/Jeffs Awesome Deck/
DELETE: api/collect/publish-deck/Jeffs Awesome Deck/

Note: There can be only one published deck and delete will delete it even if the name does not match.
