### ISSUE TITLE
Create webpage for logging a user in

### ISSUE THREAD

**Issue by wdavids1** [jricha22/cs6920#6]

**Comment by jricha22** [comment]
We are using session based auth. The way this should work is this:

When the web app starts up it should try and retrieve the current profile (API call).  If the get on the profile returns a 403 status code, the user is not logged in and either a login page should be shown or a login button added to the nav bar.  The user can log in by calling the login API, this will set the session cookie.  There should be a logout button that calls the logout API which will invalidate the session cookie.  The API should update accordingly (profile deleted, login button shown or taken to login page).
